import re
from playwright.sync_api import sync_playwright, expect
def test_code():
    with sync_playwright() as p:
        browser = p.chromium.launch(channel="chrome", headless=False)
        page = browser.new_page()
        page.goto("https://demo.pricefx.com/app/?partition=demofx_experis#/login?redirect_url=%2Fqc%2Fquotes")
        assert page.url.startswith("https://demo.pricefx.com")
        page.wait_for_timeout(3000)
        expect(page.locator("div").filter(has_text="Login").nth(5)).to_be_visible()
        expect(page.locator("[data-test=\"login-username-field\"]")).to_contain_text("Username")
        page.locator("[data-test=\"username-input\"]").click()
        page.locator("[data-test=\"username-input\"]").fill("shreyas")
        expect(page.locator("div").filter(has_text="Password").nth(5)).to_be_visible()
        page.locator("[data-test=\"password-input\"]").click()
        page.locator("[data-test=\"password-input\"]").fill("Start123!")
        expect(page.locator("[data-test=\"login-loginbutton-button\"]")).to_be_visible()
        page.locator("[data-test=\"login-loginbutton-button\"]").click()
        page.wait_for_timeout(5000)
        expect(page.get_by_text("demofx_experisQuotingQuotes")).to_be_visible()
        page.locator("[data-test=\"priceshop-newquotename-button\"]").click()
        expect(page.get_by_role("link", name="Automation_Quote")).to_be_visible()
        page.wait_for_timeout(5000)
        page.get_by_role("link", name="Automation_Quote").click()
        expect(page.get_by_text("(New Quote)")).to_be_visible()
        expect(page.get_by_text("Effective Date")).to_be_visible()
        page.locator("[data-test=\"targetdate-input\"]").click()
        page.get_by_role("button", name="2026").click()
        page.get_by_text("2025").click()
        page.get_by_text("1").nth(2).click()
        expect(page.get_by_text("Expiry Date")).to_be_visible()
        page.locator("[data-test=\"expirydate-input\"]").click()
        page.get_by_text("Today").nth(1).click()
        page.wait_for_timeout(3000)
        page.locator("[data-test=\"customer-select-addon\"]").click()
        page.locator("[data-test=\"quick-filter-Customer-Id-input\"]").get_by_role("textbox", name="Search…").click()
        page.locator("[data-test=\"quick-filter-Customer-Id-input\"]").get_by_role("textbox", name="Search…").fill(
            "CH-0001")
        ##page.locator("[data-test=\"quick-filter-Customer-Id-input\"]").get_by_role("textbox", name="Search…").press(
          ##  "Enter")
        ##page.get_by_role("row", name="Press SHIFT+SPACE to select").get_by_label("", exact=True).click()
        page.locator("[data-test=\"quick-filter-Customer-Id-input\"]").get_by_role("textbox", name="Search…").fill(
            "CH-0001")
        page.locator("[data-test=\"quick-filter-Customer-Id-input\"]").get_by_role("textbox", name="Search…").press(
            "Enter")
        page.wait_for_timeout(2000)
        page.get_by_role("row").filter(has_text="CH-0001").get_by_label("").first.click()
        page.get_by_text("Select item").click()
        expect(page.get_by_text("Quote Discount Percent")).to_be_visible()
        page.locator("[id=\"Detail-:QuoteDiscountPercent\"]").click()
        expect(page.get_by_text("Biggest")).to_be_visible()
        page.get_by_text("Biggest").click()
        page.locator("[data-test=\"Q-detail-tab--items\"]").click()
        expect(page.get_by_text("Start by adding an item")).to_be_visible()
        page.locator("[data-test=\"sfdc-import-add-items-button\"]").click()
        expect(page.get_by_role("button", name="S1250 SEAL")).to_be_visible()
        page.get_by_role("button", name="S1250 SEAL").click()
        expect(page.get_by_text("\"00000509 S1250 SEAL\" has")).to_be_visible()
        page.get_by_role("row", name="Press SHIFT+SPACE to select").get_by_label("", exact=True).click()
        expect(page.locator("[data-test=\"product-discount-percent-%-field\"]").get_by_text(
        "Product Discount Percent %")).to_be_visible()
        page.locator("[data-test=\"productdiscountpercent-input\"]").click()
        page.locator("[data-test=\"productdiscountpercent-input\"]").fill("10")
        page.locator("div").filter(has_text=re.compile(r"^QuantityProduct Discount Percent %$")).nth(2).click()
        expect(page.locator("[data-test=\"priceshop-recalculate-button\"]")).to_be_visible()
        page.locator("[data-test=\"priceshop-recalculate-button\"]").click()
        expect(page.get_by_text("Quote calculated successfully")).to_be_visible()
        expect(page.locator("[data-test=\"creationworkflow-finish-button\"]")).to_be_visible()
        page.locator("[data-test=\"creationworkflow-finish-button\"]").click()
        expect(page.get_by_text("Submit confirmation")).to_be_visible()
        page.get_by_role("textbox", name="Your comment (optional)").click()
        page.get_by_role("textbox", name="Your comment (optional)").fill("Test")
        page.locator("[data-test=\"common-submit-button\"]").click()
        expect(page.get_by_text("Quote submitted successfully")).to_be_visible()
        expect(page.get_by_text("Draft - Submitted")).to_be_visible()
        expect(page.locator("[data-test=\"Q-detail-tab--workflow\"]")).to_be_visible()
        page.locator("[data-test=\"Q-detail-tab--workflow\"]").click()
        expect(page.get_by_text("Workflow Submitted by shreyas")).to_be_visible()
        page.locator(
        ".ucButton.ucButton--hasIcon.ucButton--iconOnly.ucButton--iconOnlyColor-green > .ucButton__inner").click()
        expect(page.get_by_text("Add Approval Reason")).to_be_visible()
        page.get_by_role("textbox", name="Reason for your decision").click()
        page.get_by_role("textbox", name="Reason for your decision").fill("Test")
        page.locator("[data-test=\"common-approve-button\"]").click()
        expect(page.get_by_text("Quote has been approved")).to_be_visible()
        expect(page.get_by_role("button", name="Deal - Approved")).to_be_visible()
        browser.close()
