import playwright
# or, more typically for Playwright with pytest:
from playwright.sync_api import Playwright, sync_playwright, expect

def test_dashboard():
    with sync_playwright() as p:
        browser = p.chromium.launch(channel="chrome", headless=False)
        page = browser.new_page()
        page.goto("https://demo.pricefx.com/app/?partition=demofx_experis#/login?redirect_url=%2Fqc%2Fquotes")
        page.locator("[data-test=\"username-input\"]").click()
        page.locator("[data-test=\"username-input\"]").fill("shreyas")
        page.locator("[data-test=\"password-input\"]").click()
        page.locator("[data-test=\"password-input\"]").fill("Start123!")
        page.locator("[data-test=\"login-loginbutton-button\"]").click()
        page.goto("https://demo.pricefx.com/app/?partition=demofx_experis#/qc/quotes")
        page.locator("[data-test=\"appheader-togglebutton\"]").click()
        page.get_by_role("link", name="Dashboards").click()
        page.locator("[data-test=\"appheader-togglebutton\"]").press("Tab")
        page.locator(".ant-select-selector").click()
        page.get_by_text("AutomationDashboard").nth(2).click()
        expect(page.get_by_text("AutomationDashboard").nth(3)).to_be_visible()
        page.locator("[data-test=\"fromdate-input\"]").click()
        page.get_by_role("button", name="2020").click()
        page.get_by_text("2020", exact=True).click()
        page.get_by_text("1", exact=True).first.click()
        expect(page.get_by_text("To Date")).to_be_visible()
        page.locator("[data-test=\"todate-input\"]").click()
        page.get_by_role("button", name="2025").click()
        page.get_by_text("2025", exact=True).click()
        page.get_by_role("table").get_by_text("31", exact=True).click()
        expect(page.get_by_text("Customer", exact=True)).to_be_visible()
        page.get_by_text("CID-").click()
        page.locator("[data-test=\"customer-select\"]").get_by_role("combobox").fill("CID-00038")
        page.get_by_text("CID-").nth(2).click()
        expect(page.locator("[data-test=\"product-field\"]").get_by_text("Product")).to_be_visible()
        page.get_by_text("MB-").click()
        page.locator("[data-test=\"product-select\"]").get_by_role("combobox").fill("MB-0060")
        page.get_by_text("MB-").nth(2).click()
        expect(page.locator("[data-test=\"unity-dashboard-apply-settings-button\"]")).to_be_visible()
        page.locator("[data-test=\"unity-dashboard-apply-settings-button\"]").click()
        expect(page.get_by_text("DashBoard", exact=True)).to_be_visible()
        page.locator("[data-test=\"common-expand-button\"]").click()
        page.locator("[data-test=\"dashboard-modal\"] [data-test=\"button-menu-more-button\"]").click()
        page.get_by_role("button", name="Export to Excel").nth(1).click()
        page.wait_for_timeout(10000)
        browser.close()
